- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER # here user is a  variable the gets output from above command

  - name: print the user information
    ansible.buitlin.debug:
      msg: "user info {{ USER }}"

