- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to upper case
    vars:
      greeting: " hello aarush anish "
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lower case
    vars:
      greeting: " hello AARUSH ANISH "
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
