- name: command vs shell
  hosts: local
  connections: localhost
  tasks:
  - name: execute the shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # login to the server and execute command inside
     # command is secure then shell
  - name: check the process
    ansible.builtin.command:
    register: output
